name: Application-CI #Name of the Workflow
on: # Defined Event Trigger
  push:
    branches: [ master ]
jobs: # Jobs under which it runs the Steps
  build:
    runs-on: windows-latest #Runner Declaration
    steps: # Defined Steps
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: write-host Hello, world!
